# Generated by Django 6.0.2 on 2026-02-16 11:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_worker_user'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='hired_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data zatrudnienia'),
        ),
        migrations.CreateModel(
            name='EmploymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Organizacja')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_periods', to='business.worker', verbose_name='Pracownik')),
            ],
            options={
                'verbose_name': 'Okres zatrudnienia',
                'verbose_name_plural': 'Okresy zatrudnienia',
                'ordering': ['-start_date'],
            },
        ),
    ]
