# Generated by Django 6.0.2 on 2026-02-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0005_timesheethistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-is_default", "name"],
                "verbose_name": "Projekt",
                "verbose_name_plural": "Projekty",
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="client",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_base",
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Opis"),
        ),
        migrations.AddField(
            model_name="project",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Domyślny projekt do ewidencji czasu pracy",
                verbose_name="Domyślny",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planowany"),
                    ("ACTIVE", "Aktywny"),
                    ("COMPLETED", "Zakończony"),
                ],
                default="PLANNED",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
