# Generated by Django 6.0.2 on 2026-02-25 14:22

from django.db import migrations


def create_default_projects(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    Project = apps.get_model("business", "Project")
    WorkLog = apps.get_model("business", "WorkLog")

    for org in Organization.objects.all():
        default_project, created = Project.objects.get_or_create(
            organization=org,
            name="Ogólny",
            defaults={"is_default": True, "status": "ACTIVE"},
        )
        if not created and not default_project.is_default:
            default_project.is_default = True
            default_project.save()

        WorkLog.objects.filter(organization=org, project__isnull=True).update(
            project=default_project
        )


def reverse_default_projects(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0006_alter_project_options_remove_project_client_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_projects, reverse_default_projects),
    ]
