# Generated by Django 6.0.2 on 2026-02-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0007_create_default_projects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="description",
        ),
        migrations.AddField(
            model_name="project",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Adres"),
        ),
    ]
