# Generated by Django 6.0.2 on 2026-02-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0008_remove_project_description_project_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data zakończenia"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data rozpoczęcia"
            ),
        ),
    ]
