# Generated by Django 6.0.2 on 2026-02-27 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0010_wallet_wallettransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="business.wallet",
                verbose_name="Portfel",
            ),
        ),
    ]
