# Generated by Django 6.0.2 on 2026-02-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0011_alter_wallettransaction_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="receipt_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="receipts/%Y/%m/%d/",
                verbose_name="Zdjęcie paragonu/dowodu",
            ),
        ),
    ]
