# Generated by Django 6.0.2 on 2026-02-27 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0012_wallettransaction_receipt_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="balance",
        ),
    ]
