# Generated by Django 6.0.2 on 2026-02-27 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0013_remove_wallet_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="business.project",
                verbose_name="Projekt (opcjonalnie dla wydatków)",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FUEL", "Paliwo"),
                    ("MATERIAL", "Materiały"),
                    ("EQUIPMENT", "Narzędzia / Sprzęt"),
                    ("FOOD", "Posiłki"),
                    ("OTHER", "Inne"),
                ],
                max_length=20,
                null=True,
                verbose_name="Kategoria",
            ),
        ),
    ]
