# Generated by Django 6.0.2 on 2026-02-27 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0014_wallettransaction_project_and_more"),
        ("core", "0002_user_visible_workers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data początkowa")),
                ("end_date", models.DateField(verbose_name="Data końcowa")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data aktualizacji"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacations",
                        to="core.organization",
                        verbose_name="Organizacja",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacations",
                        to="business.worker",
                        verbose_name="Pracownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Urlop",
                "verbose_name_plural": "Urlopy",
                "ordering": ["-start_date", "worker"],
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField(verbose_name="Miesiąc")),
                ("year", models.PositiveSmallIntegerField(verbose_name="Rok")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Szkic"), ("CLOSED", "Zamknięta")],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=6,
                        verbose_name="Suma godzin",
                    ),
                ),
                (
                    "hourly_rate_snapshot",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Zapisana stawka (PLN)"
                    ),
                ),
                (
                    "gross_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Wypracowano (Brutto)",
                    ),
                ),
                (
                    "advances_deducted",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Potrącone zaliczki",
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Do wypłaty (Netto)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data wygenerowania"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data aktualizacji"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to="core.organization",
                        verbose_name="Organizacja",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to="business.worker",
                        verbose_name="Pracownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wypłata",
                "verbose_name_plural": "Wypłaty",
                "ordering": ["-year", "-month", "worker"],
                "unique_together": {("worker", "year", "month")},
            },
        ),
    ]
