# Generated by Django 6.0.2 on 2026-02-28 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_vacation_payroll'),
        ('core', '0002_user_visible_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('amount', models.PositiveIntegerField(help_text='Kwota dla każdego pracownika', verbose_name='Kwota premii (PLN)')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_days', to='core.organization', verbose_name='Organizacja')),
            ],
            options={
                'verbose_name': 'Dzień premiowy',
                'verbose_name_plural': 'Dni premiowe',
                'ordering': ['-date'],
                'unique_together': {('organization', 'date')},
            },
        ),
    ]
