# Generated by Django 6.0.2 on 2026-02-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_bonusday'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bonusy'),
        ),
    ]
